name: Deploy to GCE
on:
  push:
    branches:
      - main
jobs:
  deploy-to-gce:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: List dir
        run: ls
      - 
        name: docker-compose-build
        run: docker compose build
      - 
        name: export-docker-image
        run: docker save -o image.tar cloud_burger_backend
      -
        name: ls
        run: ls