name: Deploy to GCE
on:
  push:
    branches:
      - main
jobs:
  deploy-to-gce:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: List dir
        run: ls
      - 
        name: docker-compose-build
        run: docker compose build
      - 
        name: export-docker-image
        run: docker save -o image.tar cloud_burger_backend
      -
        name: ssh
        env:
            PRIVATE_KEY: ${{ secrets.GCE_P_KEY  }}
            HOSTNAME : ${{ secrets.GCE_IP  }}
            USER_NAME : ${{ secrets.GCE_USER_NAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key -o "StrictHostKeyChecking no" image.tar $USER_NAME@$HOSTNAME:cloud_burger_cicd 
          ssh -i private_key -o "StrictHostKeyChecking no" $USER_NAME@$HOSTNAME 'cd cloud_burger_cicd && sudo docker load -i image.tar && sudo docker run -d -p 8080:8080 cloud_burger_backend:latest'
          
