name: Deploy to GCE
on:
  push:
    branches:
      - main
jobs:
  deploy-to-gce:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: List dir
        uses: ls