name: Cloud Burger Backend CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
   